apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstore.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "bookstore.name" . }} 
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "bookstore.name" . }}
        chart: {{ include "bookstore.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: bookstore
        image: {{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}
        imagePullPolicy: {{ .Values.image.app.pullPolicy }}
        ports:
        - containerPort: 3000