apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstore.fullname" . }}-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "bookstore.name" . }}-mongodb
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "bookstore.name" . }}-mongodb
        chart: {{ include "bookstore.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.image.mongodb.repository }}:{{ .Values.image.mongodb.tag}}
        imagePullPolicy: {{ .Values.image.mongodb.pullPolicy }}
        ports:
        - name: mongodbport
          containerPort: 27017
          protocol: TCP