apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bookstore-operator
  template:
    metadata:
      labels:
        name: bookstore-operator
    spec:
      serviceAccountName: bookstore-operator
      containers:
        - name: bookstore-operator
          image: ankitcharolia/bookstore-operator:0.0.2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bookstore-operator"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstore-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookstore-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - bookstore-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - charolia.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bookstore-operator
subjects:
- kind: ServiceAccount
  name: bookstore-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: bookstore-operator
  apiGroup: rbac.authorization.k8s.io